spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s # This configuration sets the connection timeout for Redis to 2000 milliseconds (2 seconds). This means that if the application is unable to establish a connection to the Redis server within this time frame, it will throw a timeout exception. Setting an appropriate connection timeout can help to improve the responsiveness of the application and prevent it from hanging indefinitely when trying to connect to an unresponsive Redis server.
      timeout: 4s
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lowerCaseServiceId: true
              enabled: false # This configuration enables the service discovery feature of Spring Cloud Gateway, allowing it to automatically discover and route requests to other services registered with the service registry (e.g., Eureka). This can simplify the configuration of routes and make it easier to manage the routing of requests in a microservices architecture.
      httpclient:
        connect-timeout: 5000 # This configuration sets the connection timeout for the HTTP client used by Spring Cloud Gateway to 5000 milliseconds (5 seconds). This means that if the gateway is unable to establish a connection to a downstream service within this time frame, it will throw a timeout exception. Setting an appropriate connection timeout can help to improve the responsiveness of the gateway and prevent it from hanging indefinitely when trying to connect to an unresponsive service.
        response-timeout: 10s # This configuration sets the response timeout for the HTTP client used by Spring Cloud Gateway to 5000 milliseconds (5 seconds). This means that if the gateway does not receive a response from a downstream service within this time frame after successfully establishing a connection, it will throw a timeout exception. Setting an appropriate response timeout can help to improve the responsiveness of the gateway and prevent it from hanging indefinitely when waiting for a response from an unresponsive service.
management:
  info:
    env:
      enabled: true # This configuration enables the inclusion of environment information in the application's info endpoint. This can be useful for debugging and monitoring purposes, as it allows you to see the active profiles, property sources, and other environment details when accessing the /actuator/info endpoint.
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted # This configuration allows unrestricted access to the gateway endpoint, which provides information about the routes and filters configured in the API gateway. This can be useful for monitoring and debugging purposes, but in a production environment, you should consider restricting access to this endpoint for security reasons.
# The "info" section is used to provide metadata about the application, such as its name, description, and version. This information can be useful for monitoring and management purposes, as it allows you to easily identify the service and its version when viewing the application's health and status in a monitoring tool or dashboard.
info:
  app:
    name: "gatewayserver"
    description: "This service serves as the API gateway for the financial services application, routing requests to the appropriate microservices and providing a single entry point for clients."
    version: "1.0.0"

logging:
  level:
    com:
      configuration:
        gatewayserver: DEBUG # This configuration sets the logging level for the "com.configuration.gatewayserver" package to DEBUG, which means that all log messages at the DEBUG level and above (INFO, WARN, ERROR) will be logged for this package. This can be useful for troubleshooting and debugging purposes, as it allows you to see detailed log messages from the gateway server during development and testing. However, in a production environment, you may want to set the logging level to a higher level (e.g., INFO or WARN) to reduce the amount of log output and improve performance.

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 # This configuration sets the size of the sliding window for the circuit breaker to 10, which means that the circuit breaker will consider the last 10 calls to determine whether to open or close the circuit. This can help to smooth out fluctuations in call success rates and provide a more stable behavior for the circuit breaker.
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

