services:
  network-deploy-service:
    networks:
      - financial-services
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILES_ACTIVE: qa
        #      SPRING_RABBITMQ_HOST: rabbit # Required because the microservices need to connect to the RabbitMQ server using the hostname "rabbit" as defined in the docker-compose.yml file. This allows the microservices to communicate with the RabbitMQ server for messaging and event-driven communication.
      # SPRING_RABBITMQ_PORT: 5672 # This is not required because the default port for RabbitMQ is already 5672, so it will be used automatically if not specified.
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.22.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318 # This configuration sets the endpoint for the OpenTelemetry OTLP exporter to "http://tempo:4318". This means that the application will send its telemetry data (traces, metrics, and logs) to the OpenTelemetry Collector running at this endpoint. The OpenTelemetry Collector can then process and export this data to various backends for monitoring and analysis.
      OTEL_LOGS_EXPORTER: none
      OTEL_METRICS_EXPORTER: none
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  #      SPRING_DATASOURCE_USERNAME: root
  #      SPRING_DATASOURCE_PASSWORD: root

  microservice-eurekaserver-config:
    extends:
      service: micrservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root