services:
  network-deploy-service:
    networks:
      - financial-services
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILES_ACTIVE: prod
        #      SPRING_RABBITMQ_HOST: rabbit # Required because the microservices need to connect to the RabbitMQ server using the hostname "rabbit" as defined in the docker-compose.yml file. This allows the microservices to communicate with the RabbitMQ server for messaging and event-driven communication.
      # SPRING_RABBITMQ_PORT: 5672 # This is not required because the default port for RabbitMQ is already 5672, so it will be used automatically if not specified.
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  #      SPRING_DATASOURCE_USERNAME: root
  #      SPRING_DATASOURCE_PASSWORD: root

  microservice-eurekaserver-config:
    extends:
      service: micrservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root