apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki
  - name: Tempo

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: f
    uid: prometheus
    basicAuth: false
    orgId: 1
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  - name: Loki
    type: loki
    access: proxy
    url: http://gateway:3100
    uid: loki
    orgId: 1
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3100
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
